const BTC_NETWORK = process.env.REACT_APP_BTC_NETWORK
const USE_WEB_WORKERS = process.env.NODE_ENV !== 'test'
const IS_PROD_ENV = process.env.NODE_ENV === 'production'
const MAINNET_ELECTRUM_SERVERS = process.env.MAINNET_ELECTRUM_SERVERS.split(',')
const TESTNET_ELECTRUM_SERVERS = process.env.TESTNET_ELECTRUM_SERVERS.split(',')
const MAINNET_MINTLAYER_SERVERS =
  process.env.MAINNET_MINTLAYER_SERVERS.split(',')
const TESTNET_MINTLAYER_SERVERS =
  process.env.TESTNET_MINTLAYER_SERVERS.split(',')

export {
  BTC_NETWORK,
  USE_WEB_WORKERS,
  IS_PROD_ENV,
  MAINNET_ELECTRUM_SERVERS,
  TESTNET_ELECTRUM_SERVERS,
  MAINNET_MINTLAYER_SERVERS,
  TESTNET_MINTLAYER_SERVERS,
}
