const BTC_NETWORK = process.env.REACT_APP_BTC_NETWORK
const USE_WEB_WORKERS = process.env.NODE_ENV !== 'test'
const IS_PROD_ENV = process.env.NODE_ENV === 'production'
const ELECTRUM_SERVERS = process.env.ELECTRUM_SERVERS.split(',')
const PLAUSIBLE_DOMAIN = process.env.PLAUSIBLE_DOMAIN
const PLAUSIBLE_TRACK_LOCALHOST = process.env.PLAUSIBLE_LOCALHOST

export {
  BTC_NETWORK,
  USE_WEB_WORKERS,
  IS_PROD_ENV,
  ELECTRUM_SERVERS,
  PLAUSIBLE_DOMAIN,
  PLAUSIBLE_TRACK_LOCALHOST,
}
