// Mojito BE — mock data
const BE_ACCOUNTS = [
  {
    id: 'a1',
    name: 'Main',
    color: 'var(--amber)',
    btc: 'bc1q9xw5dg4yr3zarv0c5e2wfjn8kh6mua7ltd0s3j',
    ml: 'mtc1qkrz6c0d8f4h2j9l5n3p7s2v0w6x8z2a4c8e0g',
  },
  {
    id: 'a2',
    name: 'Savings',
    color: 'var(--teal)',
    btc: 'bc1qm4x2l7sp0f8v9t3k5wn6r1z8ye2ju4hq7c9d0a',
    ml: 'mtc1q7v2e9c4n8k1s5p3l0w6x8z2m4a6b8d0f2h4j6',
  },
  {
    id: 'a3',
    name: 'dApp testing',
    color: 'var(--violet)',
    btc: 'bc1qz8r5e2w9k4n1v6h3j7l0p2s5d8f1g4a7c0b3m6',
    ml: 'mtc1qa3c5e7g9j1l3n5p7r9t1v3x5z7b9d1f3h5k7m9',
  },
]

const BE_PRICES = { BTC: 96420.32, ML: 0.342 }

// Coins + Mintlayer fungible tokens. `authority` marks tokens issued by this wallet.
const BE_ASSETS = [
  {
    id: 'btc',
    sym: 'BTC',
    name: 'Bitcoin',
    chain: 'Bitcoin',
    amount: 0.0482,
    price: 96420.32,
    change: 2.18,
    spark: [100, 102, 99, 105, 108, 106, 112, 110, 115],
    decimals: 8,
  },
  {
    id: 'ml',
    sym: 'ML',
    name: 'Mintlayer',
    chain: 'Mintlayer',
    amount: 12480.5,
    price: 0.342,
    change: 8.42,
    spark: [80, 82, 78, 85, 90, 95, 92, 98, 105],
    decimals: 11,
  },
  {
    id: 'usdt',
    sym: 'USDT',
    name: 'Tether (Mintlayer)',
    chain: 'Mintlayer',
    amount: 1240,
    price: 1,
    change: 0.01,
    spark: [100, 100, 100, 100, 100, 100, 100, 100, 100],
    decimals: 6,
    tokenId: 'tmltk1qx8v3e...9k2p',
    supply: '48,201,000',
    ticker: 'USDT',
  },
  {
    id: 'cbeat',
    sym: 'CBEAT',
    name: 'Cryptobeat',
    chain: 'Mintlayer',
    amount: 5820,
    price: 0.3,
    change: 12.4,
    spark: [60, 64, 70, 68, 74, 80, 86, 84, 92],
    decimals: 2,
    tokenId: 'tmltk1q2c7d9a...4hm3',
    supply: '1,000,000',
    ticker: 'CBEAT',
    authority: true,
    mintable: true,
    frozen: false,
    lockedSupply: false,
  },
  {
    id: 'sky',
    sym: 'SKY',
    name: 'SkyToken',
    chain: 'Mintlayer',
    amount: 340,
    price: 2.62,
    change: -2.1,
    spark: [100, 98, 96, 99, 95, 92, 94, 90, 91],
    decimals: 4,
    tokenId: 'tmltk1qs5k7y3n...2xw8',
    supply: '250,000',
    ticker: 'SKY',
    hidden: false,
  },
  {
    id: 'dust',
    sym: 'AIRD',
    name: 'Airdrop Token',
    chain: 'Mintlayer',
    amount: 15,
    price: 0,
    change: 0,
    spark: [1, 1, 1, 1, 1, 1, 1, 1, 1],
    decimals: 0,
    tokenId: 'tmltk1qairdr0p...z9q1',
    supply: '∞',
    ticker: 'AIRD',
    hidden: true,
  },
]

const BE_NFTS = [
  {
    id: 'n1',
    name: 'Punk6529 #17',
    collection: 'Punk6529',
    tokenId: 'tmltk1qnft9x2v...7p4k',
    creator: 'mtc1q7v2e…4j6',
    desc: 'Generative pixel portrait from the Punk6529 series on Mintlayer.',
    hue: 290,
  },
  {
    id: 'n2',
    name: 'Cryptobeat #341',
    collection: 'Cryptobeats',
    tokenId: 'tmltk1qnft3c1b...2w9m',
    creator: 'mtc1qkrz6…8e0g',
    desc: 'One-of-one audio-visual loop. 128 BPM.',
    hue: 195,
    mine: true,
  },
  {
    id: 'n3',
    name: 'Mintlayer Genesis Pass',
    collection: 'ML Genesis',
    tokenId: 'tmltk1qnftgen...0s1s',
    creator: 'mtc1qgen…0a1b',
    desc: 'Early supporter pass. Grants access to the Genesis channel.',
    hue: 70,
  },
  {
    id: 'n4',
    name: 'Sky #102',
    collection: 'Skies',
    tokenId: 'tmltk1qnftsky1...02xx',
    creator: 'mtc1qsky…12ab',
    desc: 'Atmospheric study, 2026.',
    hue: 230,
  },
]

const BE_ACTIVITY = [
  {
    id: 't1',
    type: 'receive',
    sym: 'BTC',
    chain: 'Bitcoin',
    amount: 0.0052,
    usd: 501.4,
    when: 'Today, 09:14',
    status: 'Confirming',
    conf: '2/6',
    hash: 'a94f2c…e81b',
    from: 'bc1qm4x…9d0a',
  },
  {
    id: 't2',
    type: 'send',
    sym: 'ML',
    chain: 'Mintlayer',
    amount: 120,
    usd: 41.04,
    when: 'Today, 08:02',
    status: 'Confirmed',
    hash: '0x4f2a…b91c',
    to: 'mtc1q7v2…4j6',
    fee: '0.2 ML',
  },
  {
    id: 't3',
    type: 'mint',
    sym: 'CBEAT',
    chain: 'Mintlayer',
    amount: 1000,
    usd: 300,
    when: 'Yesterday',
    status: 'Confirmed',
    hash: '0x91cd…77ae',
    fee: '100 ML',
  },
  {
    id: 't4',
    type: 'nft',
    sym: 'NFT',
    chain: 'Mintlayer',
    name: 'Cryptobeat #341',
    when: 'Yesterday',
    status: 'Confirmed',
    hash: '0x1b2c…0f9e',
    fee: '0.3 ML',
  },
  {
    id: 't5',
    type: 'dapp',
    sym: 'ML',
    chain: 'Mintlayer',
    amount: 45,
    usd: 15.39,
    when: 'Sep 2',
    status: 'Confirmed',
    hash: '0x7aa1…c3d2',
    to: 'app.mintlayer.dex',
    fee: '0.2 ML',
  },
  {
    id: 't6',
    type: 'receive',
    sym: 'ML',
    chain: 'Mintlayer',
    amount: 2500,
    usd: 855,
    when: 'Aug 30',
    status: 'Confirmed',
    hash: '0xe5f0…12ab',
    from: 'mtc1qa3c…7m9',
  },
  {
    id: 't7',
    type: 'send',
    sym: 'BTC',
    chain: 'Bitcoin',
    amount: 0.012,
    usd: 1157,
    when: 'Aug 28',
    status: 'Failed',
    hash: '3c1d9a…4b77',
    to: 'bc1qz8r…3m6',
    fee: '1,240 sat',
  },
]

const BE_SITES = [
  {
    origin: 'app.mintlayer.dex',
    name: 'Mintlayer DEX',
    hue: 195,
    accounts: ['a1'],
    since: 'Aug 12',
  },
  {
    origin: 'bridge.mojito.finance',
    name: 'Mojito Bridge',
    hue: 290,
    accounts: ['a1', 'a3'],
    since: 'Aug 3',
  },
  {
    origin: 'mint.cryptobeats.xyz',
    name: 'Cryptobeats Mint',
    hue: 70,
    accounts: ['a3'],
    since: 'Jul 21',
  },
]

// dApp request fixtures
const BE_REQUESTS = {
  connect: {
    kind: 'connect',
    origin: 'app.mintlayer.dex',
    name: 'Mintlayer DEX',
    hue: 195,
    perms: [
      'See your address, balance and activity',
      'Request approval for transactions',
      'Request message signatures',
    ],
  },
  sign: {
    kind: 'sign',
    origin: 'app.mintlayer.dex',
    name: 'Mintlayer DEX',
    hue: 195,
    message:
      'Sign in to Mintlayer DEX\n\nNonce: 8f3a91c2\nIssued: 2026-09-05T12:06:43Z\n\nThis request will not trigger a blockchain transaction or cost any fees.',
  },
  tx: {
    kind: 'tx',
    origin: 'app.mintlayer.dex',
    name: 'Mintlayer DEX',
    hue: 195,
    chain: 'Mintlayer',
    sym: 'ML',
    amount: 45,
    to: 'mtc1qdexp00l7v2e9c4n8k1s5p3l0w6x8z2m4a6b8',
    fee: 0.2,
    data: 'OrderFill{ pair: ML/USDT, side: buy, qty: 45, limit: 0.342 }',
  },
  btctx: {
    kind: 'tx',
    origin: 'bridge.mojito.finance',
    name: 'Mojito Bridge',
    hue: 290,
    chain: 'Bitcoin',
    sym: 'BTC',
    amount: 0.0021,
    to: 'bc1qbridge7sp0f8v9t3k5wn6r1z8ye2ju4hq7c9d',
    fee: 0.000012,
    data: 'OP_RETURN 6d6c2d6272696467652d31',
  },
  network: {
    kind: 'network',
    origin: 'mint.cryptobeats.xyz',
    name: 'Cryptobeats Mint',
    hue: 70,
    from: 'Mainnet',
    to: 'Testnet',
  },
  token: {
    kind: 'token',
    origin: 'mint.cryptobeats.xyz',
    name: 'Cryptobeats Mint',
    hue: 70,
    ticker: 'BEATS',
    tokenId: 'tmltk1qb3a7s9v2e...0k1m',
    decimals: 4,
    supply: '10,000,000',
  },
  delegate: {
    kind: 'delegate',
    origin: 'app.mintlayer.dex',
    name: 'Mintlayer DEX',
    hue: 195,
    pool: 'mpool1q9xw5…7ltd',
    amount: 500,
    fee: 0.2,
  },
}

const BE_SEED = [
  'ancient',
  'bridge',
  'canyon',
  'anchor',
  'coconut',
  'circle',
  'credit',
  'crystal',
  'autumn',
  'balance',
  'beach',
  'bench',
  'camera',
  'castle',
  'ceiling',
  'century',
  'cherry',
  'clever',
  'cliff',
  'cluster',
  'coral',
  'cotton',
  'crane',
  'brave',
]

const fmtUsd = (n) =>
  '$' +
  n.toLocaleString(undefined, {
    minimumFractionDigits: 2,
    maximumFractionDigits: 2,
  })
const fmtAmt = (n, d = 4) =>
  n.toLocaleString(undefined, { maximumFractionDigits: d })
const shortAddr = (a, n = 8) =>
  a.length > n * 2 + 1 ? a.slice(0, n) + '…' + a.slice(-n + 2) : a

Object.assign(window, {
  BE_ACCOUNTS,
  BE_PRICES,
  BE_ASSETS,
  BE_NFTS,
  BE_ACTIVITY,
  BE_SITES,
  BE_REQUESTS,
  BE_SEED,
  fmtUsd,
  fmtAmt,
  shortAddr,
})
